version: '3.7'

networks:
  crm:
    external: true

services:
  order:
    image: order:latest
    container_name: orders
    ports:
      - "9015:9015"
    environment:
      - CONFIG_SERVER_LOGIN=user
      - CONFIG_SERVER_PASSWORD=user
      - SPRING_PROFILES_ACTIVE=default
      - CONFIG_SERVER_URI=http://user:user@settings:8888
      - DB_PASSWORD=1904
      - DB_URL=jdbc:postgresql://postgres:5432/orders
      - DB_USERNAME=postgres
      - KAFKA_URL=kafka:9092
      - USER_READER_DB_PASSWORD=1904
      - USER_READER_DB_URL=jdbc:postgresql://postgres:5432/users
      - USER_READER_DB_USERNAME=users_reader
      - REDIS_HOST_INFRASTRUCTURE=redis
      - REDIS_PORT_INFRASTRUCTURE=6379
      - REDIS_DATABASE_INFRASTRUCTURE=0
      - NOVA_POST_HOST=https://api.novaposhta.ua/v2.0/json/
      - NOVA_POST_TOKEN=07e4a86cc0f63f9ee4867b58c2034c5b
    networks:
      - crm